version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 