version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: travel-agent-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - travel-agent-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: travel-agent-keycloak
    command: 
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - travel-agent-network

volumes:
  postgres_data:

networks:
  travel-agent-network:
    driver: bridge 